version: "2"
services:
  dongtai-mysql: 
    image: dongtai/dongtai-mysql:latest
    ports:
      - "33060:3306"
    restart: always
  
  dongtai-redis:
    image: dongtai/dongtai-redis:latest
    restart: always
  dongtai-webapi:
    build: 
      context: .
      dockerfile: ./DockerfileDev
    restart: always
    ports:
      - "8000:8000"
      - "8010:8010"
    environment: 
      #      - PYTHONAGENT=TRUE
      - DOC=TRUE
      - debug=true
      - SAVEEYE=TRUE
      - PROJECT_NAME=LocalWEBAPI
      - LOG_PATH=/tmp/dongtai-agent-python.log
      - CPROFILE=TRUE
    volumes:
      - .:/opt/dongtai/webapi/

  dongtai-web:
    image: dongtai/dongtai-web:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dongtai-webapi

  dongtai-openapi:
    image: dongtai/dongtai-openapi:latest
    restart: always
    volumes:
      - ./conf/config.ini:/opt/dongtai/openapi/conf/config.ini

  dongtai-engine:
    image: dongtai/dongtai-engine:latest
    deploy:
      replicas: 0
    restart: always
    volumes:
      - ./conf/config.ini:/opt/dongtai/engine/conf/config.ini


  dongtai-engine-task:
    image: dongtai/dongtai-engine:latest
    deploy:
      replicas: 0
    restart: always
    command: ["/opt/dongtai/engine/docker/entrypoint.sh", "task"]
    volumes:
      - ./conf/config.ini:/opt/dongtai/engine/conf/config.ini
    depends_on:
      - dongtai-engine
